### ISSUE TITLE
v2 todo list

### ISSUE THREAD

**Issue by Picalines** [Picalines/godot-ldtk-import-mono#1]
Problem: writing `ImportExtension` is *too complicated*

- [ ] background color from LDtk project settings

- [ ] importer settings:
   * [ ] entity path
   * [ ] base scene

- [ ] LDtkEntityAttribute

- [ ] LDtkFieldAttribute

- [ ] entity tag for YSort entities

- [ ] json in tile custom data
   * [ ] "scene" field to replace tile with a scene
   * [ ] other fields are assigned like LDtkField

- [ ] keep TileSet collisions in Godot's editor
